# === CÓDIGO ACTUALIZADO para actualizador.yml ===

name: Actualizar Programacion Web Diariamente

on:
  schedule:
    - cron: '0 8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          # Añadimos la nueva librería de Google
          pip install requests beautifulsoup4 google-generativeai

      - name: Ejecutar script de actualizacion y subida
        env:
          # Pasamos la nueva clave API junto con las demás
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          URL_FUENTE: ${{ secrets.URL_FUENTE }}
          NOMBRE_ARCHIVO_PROGRAMACION: ${{ secrets.NOMBRE_ARCHIVO_PROGRAMACION }}
          NOMBRE_ARCHIVO_MENSAJE: ${{ secrets.NOMBRE_ARCHIVO_MENSAJE }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
          FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        run: python actualizador_web.py
