# === INICIO DEL CÓDIGO ACTUALIZADO para actualizador.yml ===

name: Actualizar Programacion Web Diariamente

on:
  # Disparador 1: Se ejecuta automáticamente según un horario.
  schedule:
    # --- HORARIO ACTUALIZADO ---
    # Se ejecuta a las 10:00, 14:00 y 18:00 UTC.
    # Esto corresponde a las 4:00 AM, 8:00 AM y 12:00 PM en tu zona horaria (CST, UTC-6).
    - cron: '0 10,14,18 * * *'
  
  # Disparador 2: Permite ejecutarlo manualmente desde la pestaña "Actions".
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar script de actualizacion y subida
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
          FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        run: python actualizador_web.py

# === FIN DEL CÓDIGO ACTUALIZADO para actualizador.yml ===
