# === INICIO DEL CÓDIGO PARA actualizador.yml ===

name: Actualizar Programacion Web Diariamente

on:
  # Disparador 1: Se ejecuta automáticamente según un horario.
  schedule:
    # Se ejecuta todos los días a las 11:00 UTC (5:00 AM hora de México Central, CST).
    # Formato: Minuto Hora(UTC) Día Mes DíaDeLaSemana
    - cron: '0 11 * * *'

  # Disparador 2: Permite ejecutarlo manualmente desde la pestaña "Actions".
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usa una máquina virtual de Linux gratuita.
    steps:
      # Paso 1: Descarga tu código del repositorio a la máquina virtual.
      - name: Checkout del codigo
        uses: actions/checkout@v4

      # Paso 2: Prepara el entorno de Python.
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Paso 3: Instala las librerías que tu script necesita.
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Paso 4: Ejecuta el script principal.
      - name: Ejecutar script de actualizacion y subida
        env:
          # Pasa los "Secrets" de forma segura al script como variables de entorno.
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
          FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        run: python actualizador_web.py

# === FIN DEL CÓDIGO PARA actualizador.yml ===
