name: Ranking de Eventos Relevantes con IA

on:
  schedule:
    - cron: '0 1,5,9,13,17,21 * * *'
  workflow_dispatch:

jobs:
  run-ranking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests beautifulsoup4 google-generativeai pytz
      - name: Ejecutar script de ranking y subida
        env:
          # Añadimos la nueva clave de Hugging Face
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
          FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        run: python ranker_gemini.py
