# Nombre de la nueva automatización
name: Buscador de Resultados de Partidos

on:
  schedule:
    # --- HORARIO ACTUALIZADO ---
    # Se ejecuta a las 20:05, 23:05, 02:05 y 05:05 UTC.
    # Corresponde a las 2:05 PM, 5:05 PM, 8:05 PM y 11:05 PM en tu zona horaria (CST, UTC-6).
    - cron: '5 2,5,20,23 * * *'
  
  # Permite ejecutarlo manualmente desde la pestaña "Actions" para pruebas.
  workflow_dispatch:

jobs:
  run-results-fetcher:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descarga el código del repositorio
      - name: Checkout del codigo
        uses: actions/checkout@v4

      # Paso 2: Configura el entorno de Python
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Paso 3: Instala las librerías necesarias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          # Añadimos la nueva librería 'pytz'
          pip install requests beautifulsoup4 google-generativeai pytz
          
      # Paso 4: Ejecuta el NUEVO script de resultados
      - name: Ejecutar script buscador de resultados
        env:
          # Pasa todos los secrets necesarios al script
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USUARIO: ${{ secrets.FTP_USUARIO }}
          FTP_CONTRASENA: ${{ secrets.FTP_CONTRASENA }}
        run: python results_fetcher.py
