name: Envio Automatico Eventos Rankeados

on:
  schedule:
    # Se ejecuta TODOS LOS DÍAS a las 8:30 AM hora de la Ciudad de México (14:30 UTC)
    # Cron: '30 14 * * *' (El asterisco al final indica 'cualquier día de la semana')
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  enviar_ranking:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        # --- LÍNEA CORREGIDA ---
        # Añadimos la librería 'pytz' que ahora es requerida por el script.
        pip install requests pytz

    - name: Ejecutar script de envio de ranking
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        URL_EVENTOS_JSON: ${{ secrets.URL_EVENTOS_JSON }}
        URL_RANKING_JSON: ${{ secrets.URL_RANKING_JSON }}
        TZ: America/Mexico_City
      run: python enviar_eventos_rankeados_telegram.py
